print("-------------------------------------------------------")
print("              Chino's Coffee Bean                      ")
print(" Date: 26 Dec 2020                                     ")
print("-------------------------------------------------------")
print("Amount |     Order                    |    Price(THB)  ")
print("1      | Chiang Dao medium            |        100.00  ")
print("1      | Chiang Dao dark              |        100.00  ")
print("1      | Brazil Honey                 |        120.00  ")
print("2      | Dao Chang organic dark       |        300.00  ")
print("2      | Chiang Dao organic medium    |        300.00  ")
print("1      | Peru medium dark             |        140.00  ")
print("2      | Costa Rica                   |        400.00  ")
print("1      | Red Java                     |        150.00  ")
print("-------------------------------------------------------")
print("Total (THB)                                  1,610.00  ")
print("-------------------------------------------------------")

